1.3-dev-0

diff --git a/custom_bin/rebuild-interactive b/custom_bin/rebuild-interactive
--- a/custom_bin/rebuild-interactive
+++ b/custom_bin/rebuild-interactive
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e # fail on any error
+
 echo -e "\nFully Rebuildan~\n"
 
 bash fullclean
